steps:
  # Reservations
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/reservations/production",
        "-f",
        "apps/reservations/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/reservations/production",
      ]

  # Auth
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/auth/production",
        "-f",
        "apps/auth/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/auth/production",
      ]

  # Notifications
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/notifications/production",
        "-f",
        "apps/notifications/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/notifications/production",
      ]

  # Payments
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/payments/production",
        "-f",
        "apps/payments/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/nestjsmicroservicenotification/payments/production",
      ]
