POST http://localhost:3021/reservations
Content-Type: application/json

{
  "startDate": "12-12/2023",
  "endDate": "12/24/2024",
  "placeId": "12345",
  "invoiceId": "499",
  "charge": {
    "amount": 5,
    "card": {
      "cvc": "413",
      "exp_month": 12,
      "exp_year": 2030,
      "number": "4242 4242 4242 4242"
    }
  }
}

###
GET http://localhost:3021/reservations

###
GET http://localhost:3021/reservations/64e50b8009aa07e482886693

###
PATCH http://localhost:3021/reservations/64e50b8009aa07e482886693
Content-Type: application/json

{
  "startDate": "12/10/2023"
}

###
DELETE http://localhost:3021/reservations/64e50b8009aa07e482886693

###
POST http://localhost:3021/reservations
Content-Type: application/json

{
  "startDate": "12-12/2023",
  "endDate": "12/24-2024",
  "placeId": "12345",
  "invoiceId": "499"
}

###
POST http://localhost:3021/reservations
Content-Type: application/json

{
  "extra":"Won't go",
  "startDate": "12-12/2023",
  "endDate": "12/24-2024",
  "placeId": "12345",
  "invoiceId": "499"
}


###########################################################

###
POST http://localhost:3022/users
Content-Type: application/json

{
  "email":"zubaku92@gmail.com",
  "password": "randomStrongPassword123_/+"
}

###
POST http://localhost:3022/users
Content-Type: application/json

{
  "email":"test@gmail.com",
  "password": "123"
}

###
GET http://localhost:3022/users

###
GET http://localhost:3022/users/all

###########################################################

###
POST http://localhost:3022/auth/login
Content-Type: application/json

{
  "email":"zubaku92@gmail.com",
  "password": "randomStrongPassword123_/+"
}