apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/nestjsmicroservicenotification/notifications/production
          name: production
          env:
            # In which env variable we need to inject
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  # Which secret to inject
                  name: mongodb
                  # Value of the secret
                  key: connectionString
