import { Injectable } from '@nestjs/common';
import { Response } from 'express';
import { User } from '@app/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { TokenPayload } from './interfaces/token-payload.interface';

@Injectable()
export class AuthService {
  constructor(
    private readonly configService: ConfigService,
    private readonly jwtService: JwtService,
  ) {}

  async login(user: User, response: Response) {
    const tokenPayload: TokenPayload = {
      userId: user.id,
    };

    const expirationDate = new Date();
    expirationDate.setSeconds(
      expirationDate.getSeconds() +
        /* I've noticed that when I send multiple login requests, the jwt tokens generated by my app have different expire dates ranging from a few days to months.
        I think in auth.service.ts, the value of JWT_EXPIRATION should be converted to Number from String.*/
        Number(this.configService.get('JWT_EXPIRATION')),
    );

    const token: string = this.jwtService.sign(tokenPayload);

    response.cookie('Authentication', token, {
      httpOnly: true,
      expires: expirationDate,
    });

    return token;
  }
}
