apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  ports:
    # If it is a microservice -> TCP, otherwise HTTP
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: reservations
  type: NodePort
